CREATE TABLE If NOT EXISTS TEAM (
	TEAM_ID INTEGER PRIMARY KEY,
	NAME TEXT NOT NULL,
	OWNER TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS WEEK (
	WEEK_ID INTEGER PRIMARY KEY,
	DESC TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS SCORE_CARD (
	TEAM_ID INTEGER,
	WEEK_ID INTEGER NOT NULL,
	AT_BATS INTEGER NOT NULL DEFAULT 0,
	RUNS INTEGER NOT NULL DEFAULT 0,
	HITS INTEGER NOT NULL DEFAULT 0,
	HOME_RUNS INTEGER NOT NULL DEFAULT 0,
	RUNS_BATTED_IN INTEGER NOT NULL DEFAULT 0,
	STOLEN_BASES INTEGER NOT NULL DEFAULT 0,
	BASE_ON_BALLS INTEGER NOT NULL DEFAULT 0,
	BATTING_STRIKEOUTS INTEGER NOT NULL DEFAULT 0,
	ERRORS INTEGER NOT NULL DEFAULT 0,
	INNINGS_PITCHED TEXT NOT NULL DEFAULT 0,
	WINS INTEGER NOT NULL DEFAULT 0,
	LOSSES INTEGER NOT NULL DEFAULT 0,
	SHUTOUTS INTEGER NOT NULL DEFAULT 0,
	SAVES INTEGER NOT NULL DEFAULT 0,
	PITCHING_STRIKE_OUTS INTEGER NOT NULL DEFAULT 0,
	HOLDS INTEGER NOT NULL DEFAULT 0,
	EARNED_RUN_AVERAGE REAL NOT NULL DEFAULT 0.00,
	WALKS_AND_HITS_PER_INNINGS_PITCHED REAL NOT NULL DEFAULT 0.00,
	QUALITY_STARTS INTEGER NOT NULL DEFAULT 0,
	FOREIGN KEY (TEAM_ID) REFERENCES TEAM (TEAM_ID)
	FOREIGN KEY (WEEK_ID) REFERENCES WEEK (WEEK_ID)
);

CREATE TABLE IF NOT EXISTS MATCHUP (
	AWAY_TEAM INTEGER NOT NULL,
	HOME_TEAM INTEGER NOT NULL,
	PRIMARY KEY (AWAY_TEAM, HOME_TEAM),
	FOREIGN KEY (AWAY_TEAM) REFERENCES SCORE_CARD (SCORE_CARD_ID),
	FOREIGN KEY (HOME_TEAM) REFERENCES SCORE_CARD (SCORE_CARD_ID)
);